Repository CrocSwap/ambient-ts-app, pull requests merged in 2023-06, with the labels that each got.

#2441 Update UI for remove range modal
  src/components/Global/Modal/Modal.module.css
  src/components/Global/RangeStatus/RangeStatus.module.css
  src/components/Global/RangeStatus/RangeStatus.tsx
  src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
  src/components/HarvestPosition/HarvestExtraControls/HarvestExtraControls.tsx
  src/components/HarvestPosition/HarvestPosition.module.css
  src/components/HarvestPosition/HarvestPosition.tsx
  src/components/HarvestPosition/HarvestPositionButton/HarvestPositionButton.tsx
  src/components/HarvestPosition/HarvestPositionHeader/HarvestPositionHeader.module.css
  src/components/HarvestPosition/HarvestPositionInfo/HarvestPositionInfo.module.css
  src/components/HarvestPosition/HarvestPositionInfo/HarvestPositionInfo.tsx
  src/components/HarvestPosition/HarvestPositionSettings/HarvestPositionSettings.tsx
  src/components/HarvestPosition/HarvestPositionTokenHeader/HarvestPositionTokenHeader.module.css
  src/components/HarvestPosition/HarvestPositionTokenHeader/HarvestPositionTokenHeader.tsx
  src/components/RangeActionModal/RangeActionButton/RangeActionButton.tsx
  src/components/RangeActionModal/RangeActionExtraControls/RangeActionExtraControls.module.css
  src/components/RangeActionModal/RangeActionExtraControls/RangeActionExtraControls.tsx
  src/components/RangeActionModal/RangeActionHeader/RangeActionHeader.module.css
  src/components/RangeActionModal/RangeActionHeader/RangeActionHeader.tsx
  src/components/RangeActionModal/RangeActionInfo/HarvestPositionInfo.tsx
  src/components/RangeActionModal/RangeActionInfo/RangeActionInfo.module.css
  src/components/RangeActionModal/RangeActionInfo/RemoveRangeInfo.tsx
  src/components/RangeActionModal/RangeActionModal.module.css
  src/components/RangeActionModal/RangeActionModal.tsx
  src/components/RangeActionModal/RangeActionSettings/RangeActionSettings.module.css
  src/components/RangeActionModal/RangeActionSettings/RangeActionSettings.tsx
  src/components/RangeActionModal/RangeActionTokenHeader/RangeActionTokenHeader.module.css
  src/components/RangeActionModal/RangeActionTokenHeader/RangeActionTokenHeader.tsx
  src/components/RangeActionModal/RemoveRangeWidth/RemoveRangeWidth.module.css
  src/components/RangeActionModal/RemoveRangeWidth/RemoveRangeWidth.tsx
  src/components/RemoveRange/ExtraControls/ExtraControls.module.css
  src/components/RemoveRange/RemoveRangeButton/RemoveRangeButton.tsx
  src/components/RemoveRange/RemoveRangeHeader/RemoveRangeHeader.tsx
  src/components/RemoveRange/RemoveRangeSettings/RemoveRangeSettings.module.css
Labels: needs-design-signoff

#2466 fix token input UI
  src/components/Global/TokenSelect/TokenSelect.module.css
  src/components/Global/TokenSelectContainer/SoloTokenSelect.module.css
  src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
Labels: needs-design-signoff

#2283 Increase scientific notation input support
  src/components/Global/TokenSelectContainer/SoloTokenImport.tsx
  src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.tsx
  src/components/Portfolio/ExchangeBalance/Transfer/TransferAddressInput/TransferAddressInput.tsx
  src/components/Portfolio/ExchangeBalance/Transfer/TransferCurrencySelector/TransferCurrencySelector.tsx
  src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawCurrencySelector/WithdrawCurrencySelector.tsx
  src/components/Swap/CurrencyQuantity/CurrencyQuantity.tsx
  src/components/Trade/Edit/AmountAndCurrencyDisplay/AmountAndCurrencyDisplay.tsx
  src/components/Trade/Edit/EditPriceInput/EditPriceInput.tsx
  src/components/Trade/Limit/LimitCurrencyQuantity/LimitCurrencyQuantity.tsx
  src/components/Trade/Limit/LimitRate/LimitRate.tsx
  src/components/Trade/Range/AdvancedModeComponents/MinMaxPrice/MinMaxPrice.tsx
  src/components/Trade/Range/AdvancedModeComponents/PriceInput/PriceInput.tsx
  src/components/Trade/Range/RangeCurrencyConverter/RangeCurrencyConverter.tsx
  src/components/Trade/Range/RangeCurrencyQuantity/RangeCurrencyQuantity.tsx
  src/pages/InitPool/InitPool.tsx
  src/pages/Trade/Range/rangeFunctions.ts
  src/pages/Trade/Reposition/Reposition.tsx
  src/utils/data/baseUrlPaths.ts
  src/utils/functions/validateAddress.ts
  src/utils/functions/validateChain.ts
  src/utils/regex/chainIdRegEx.ts
  src/utils/regex/contractAddrRegEx.ts
  src/utils/regex/decimalNumRegEx.ts
  src/utils/regex/exponentialNumRegEx.ts
  src/utils/regex/exports.ts
Labels: enhancement

#2493 Caution weth
  src/components/Global/TokenSelectContainer/SoloTokenSelect.module.css
  src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
  src/utils/data/handleWETH.ts
Labels: enhancement, look-and-feel, high-prio

#2497 Update trade table UI
  src/components/Global/Tabs/TableMenu/TableMenuComponents/TableMenus.module.css
  src/components/Global/Tabs/TableMenu/TableMenuComponents/TransactionsMenu.tsx
  src/components/Portfolio/PortfolioBanner/PortfolioBanner.module.css
  src/components/Portfolio/PortfolioTabs/PortfolioTabs.module.css
  src/components/Trade/TradeTabs/TradeTabs2.module.css
  src/components/Trade/TradeTabs/TradeTabs2.tsx
  src/components/Trade/TradeTabs/Transactions/Transactions.module.css
  src/css/GlobalCssClassnames.css
  src/pages/Portfolio/Portfolio.module.css
  src/pages/Trade/TradeCharts/TradeCharts.module.css
  src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.module.css
  src/utils/hooks/useProcessTransaction.ts
Labels: needs-design-signoff

#2503 Reposition modal UX changes
  src/components/Global/ConfirmationModalControl/ConfirmationModalControl.module.css
  src/components/Global/ContentHeader/ContentHeader.module.css
  src/components/Global/Modal/Modal.module.css
  src/components/Global/RangeStatus/RangeStatus.module.css
  src/components/Global/TransactionSettings/TransactionSettings.module.css
  src/components/Global/TransactionSettings/TransactionSettings.tsx
  src/components/Trade/Range/ConfirmRangeModal/SelectedRange/SelectedRange.module.css
  src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.module.css
  src/components/Trade/Reposition/RepositionHeader/RepositionHeader.module.css
  src/components/Trade/Reposition/RepositionHeader/RepositionHeader.tsx
  src/components/Trade/Reposition/RepositionPriceInfo/RepositionPriceInfo.module.css
  src/components/Trade/Reposition/RepositionRangeWidth/RepositionRangeWidth.module.css
  src/pages/Trade/Reposition/Reposition.module.css
  src/pages/Trade/Reposition/Reposition.tsx
Labels: needs-design-signoff

#2512 show full addresses in tx details
  src/components/Global/TransactionDetails/TransactionDetailsSimplify/TransactionDetailsSimplify.tsx
  src/utils/hooks/useProcessTransaction.ts
Labels: needs-design-signoff

#2490 Update chart tooltips UI
  src/components/Global/StyledTooltip/StyledTooltip.tsx
  src/pages/Trade/Trade.module.css
  src/pages/Trade/TradeCharts/TradeCharts.module.css
  src/pages/Trade/TradeCharts/TradeCharts.tsx
  src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.module.css
  src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx
Labels: needs-design-signoff

#2544 complete logic to insert USDC data into wallet dropdown
  src/App/components/PageHeader/Account/Account.module.css
  src/App/components/PageHeader/Account/Account.tsx
  src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.module.css
  src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx
  src/utils/tokens/USDC.ts
Labels: enhancement, look-and-feel, med-prio

#2569 change padding and added hover states to token selectors
  src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.module.css
  src/components/Portfolio/ExchangeBalance/Transfer/TransferCurrencySelector/TransferCurrencySelector.module.css
  src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawCurrencySelector/WithdrawCurrencySelector.module.css
  src/components/Swap/CurrencySelector/CurrencySelector.module.css
  src/components/Trade/Limit/LimitCurrencySelector/LimitCurrencySelector.module.css
  src/components/Trade/Range/RangeCurrencySelector/RangeCurrencySelector.module.css
Labels: needs-design-signoff
