Repository CrocSwap/ambient-ts-app, pull requests merged in 2023-08, with the labels that each got.

#2769 Exchange balance UI
  src/components/Global/TabComponent/TabComponent.module.css
  src/components/Portfolio/ExchangeBalance/ExchangeBalance.module.css
  src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx
  src/pages/Portfolio/Portfolio.module.css
Labels: needs-design-signoff

#2539 Landing changes
  package.json
  public/index.html
  public/previewImage.png
  src/App/App.tsx
  src/App/components/PageHeader/ExchangeBalanceModal/ExchangeBalanceModal.module.css
  src/App/components/PageHeader/ExchangeBalanceModal/ExchangeBalanceModal.tsx
  src/App/components/PageHeader/NavItem/NavItem.tsx
  src/App/components/PageHeader/PageHeader.tsx
  src/App/components/PageHeader/PageHeaderMobile.module.css
  src/App/components/PageHeader/PageHeaderMobile.tsx
  src/components/Footer/Footer.module.css
  src/components/Footer/Footer.tsx
  src/components/Global/PoolCard/PoolCard.module.css
  src/components/Home/Landing/Home1.module.css
  src/components/Home/Landing/Investors.module.css
  src/components/Home/Landing/Investors.tsx
  src/components/Home/Landing/LandingSections.module.css
  src/components/Home/Landing/LandingSections.tsx
  src/components/Home/Landing/MobileLandingSections.module.css
  src/components/Home/Landing/MobileLandingSections.tsx
  src/components/Home/Landing/TradeNowButton/TradeNowButton.tsx
  src/components/Home/Stats/AmbientStats.tsx
  src/components/Home/Stats/Stats.module.css
  src/components/Home/TopPools/TopPools.module.css
  src/components/Home/TopPools/TopPools.tsx
  src/components/Portfolio/ExchangeBalance/ExchangeBalance.module.css
  src/components/Trade/TradeTabs/Transactions/Transactions.module.css
  src/declarations.d.ts
  src/pages/Home/Home.module.css
  src/pages/Home/Home.tsx
  yarn.lock
Labels: needs-design-signoff

#2760 2680 enhancement recent transactions UI updates
  src/components/Global/NotificationCenter/NotificationTable/NotificationTable.module.css
  src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.module.css
  src/components/Global/NotificationCenter/ReceiptDisplay/ReceiptDisplay.tsx
Labels: needs-design-signoff

#2796 remove `POOL_COUNT` limiter from `TopPools.tsx` component file
  src/components/Global/Analytics/TopPools.tsx
Labels: enhancement, look-and-feel

#2824 Add Wallet tokens to modal
  src/App/hooks/useTokenSearch.ts
Labels: enhancement

#2775 Update account background
  src/assets/images/backgrounds/account_image.png
  src/assets/images/backgrounds/account_image.svg
  src/components/Portfolio/PortfolioBanner/PortfolioBanner.module.css
  src/index.css
Labels: needs-design-signoff

#2762 Sidebar UI
  src/App/components/Sidebar/Sidebar.module.css
  src/App/components/Sidebar/Sidebar.tsx
  src/App/components/Sidebar/SidebarAccordion.tsx
  src/App/components/Sidebar/SidebarSearchResults/SidebarSearchResults.module.css
  src/App/hooks/useSidebarSearch.ts
  src/assets/images/sidebarImages/favouritePools.svg
  src/assets/images/sidebarImages/topPools.svg
  src/components/Global/Sidebar/SidebarRangePositions/SidebarRangePositions.tsx
  src/components/Global/Sidebar/SidebarRangePositions/SidebarRangePositionsCard.module.css
  src/components/Global/Sidebar/SidebarRangePositions/SidebarRangePositionsCard.tsx
  src/styled/Sidebar/SidebarPoolsListHeaderContainer.ts
  yarn.lock
Labels: needs-design-signoff

#2802 remove wrapped native token from searches
  src/App/hooks/useTokenSearch.ts
  src/components/Global/TokenSelectContainer/SoloTokenSelectModal.module.css
  src/components/Global/TokenSelectContainer/SoloTokenSelectModal.tsx
  src/components/RangeActionModal/WarningBox/WarningBox.module.css
  src/components/RangeActionModal/WarningBox/WarningBox.tsx
  src/components/RangeDetails/RangeDetailsModal/RangeDetailsModal.tsx
  src/utils/data/handleWETH.ts
  src/utils/functions/removeWrappedNative.ts
  src/utils/tokens/exports.ts
  src/utils/tokens/wrappedNatives.ts
  yarn.lock
Labels: enhancement, look-and-feel, needs-design-signoff, needs-design

#2891 show token name as tooltip on logo on `/explore` route
  src/components/Global/TokenIcon/TokenIcon.module.css
  src/components/Global/TokenIcon/TokenIcon.tsx
Labels: enhancement

#2919 Parameterize `/initpool` page
  src/pages/InitPool/InitPool.tsx
  src/utils/data/testTokenMap.ts
Labels: enhancement
