Repository CrocSwap/ambient-ts-app, pull requests merged in 2023-07, with the labels that each got.

#2604 Migrate use pool list to pool context
  src/App/components/Sidebar/Sidebar.tsx
  src/App/components/Sidebar/useSidebarSearch/useSidebarSearch.ts
  src/App/functions/fetchPoolList.ts
  src/App/hooks/usePoolList.ts
  src/contexts/PoolContext.tsx
  src/utils/interfaces/GCServerPoolIF.ts
  src/utils/interfaces/TempPoolIF.ts
  src/utils/interfaces/exports.ts
Labels: technical debt, high-prio

#2613 Remove uninitialized pools from recent list
  src/App/components/PageHeader/PageHeader.tsx
  src/App/hooks/useRecentPools.ts
  src/components/Global/Sidebar/RecentPools/RecentPools.tsx
  src/contexts/SidebarContext.tsx
Labels: bug, med-prio

#2641 Add uniswap list to default tokens in selector
  src/App/hooks/useTokenSearch.ts
  src/App/hooks/useTokens.ts
  src/components/Global/TokenSelect/TokenSelect.module.css
  src/components/Global/TokenSelect/TokenSelect.tsx
  src/components/Global/TokenSelectContainer/SoloTokenSelect.module.css
  src/components/Global/TokenSelectContainer/SoloTokenSelect.tsx
  src/utils/functions/uriToHttp.ts
Labels: enhancement, look-and-feel, high-prio

#2653 refactor `useTokenSearch.ts` to use tiebreaker sort alphanumeric
  src/App/hooks/useTokenSearch.ts
Labels: enhancement, look-and-feel

#2657 complete logic to load token logos with react suspense
  public/ambient-token-list.json
  src/components/Global/Account/AccountTabs/Exchange/ExchangeCard.tsx
  src/components/Global/PoolCard/PoolCard.tsx
  src/components/Global/TokenIcon/TokenIcon.tsx
  src/components/Global/TokenSelect/TokenSelect.tsx
  src/components/Global/TokenSelectContainer/SoloTokenImport.tsx
  src/components/Portfolio/ExchangeBalance/Deposit/DepositCurrencySelector/DepositCurrencySelector.tsx
  src/components/Portfolio/ExchangeBalance/Transfer/TransferCurrencySelector/TransferCurrencySelector.tsx
  src/components/Portfolio/ExchangeBalance/Withdraw/WithdrawCurrencySelector/WithdrawCurrencySelector.tsx
  src/components/Swap/CurrencySelector/CurrencySelector.tsx
  src/components/Trade/Limit/LimitCurrencySelector/LimitCurrencySelector.tsx
  src/components/Trade/Range/ConfirmRangeModal/ConfirmRangeModal.tsx
  src/components/Trade/Reposition/ConfirmRepositionModal/ConfirmRepositionModal.tsx
Labels: enhancement, look-and-feel, med-prio

#2716 Remove use translation
  src/App/components/PageHeader/PageHeader.tsx
  src/App/components/Sidebar/Sidebar.tsx
  src/components/Home/Landing/TradeNowButton/TradeNowButton.tsx
  src/components/Home/Stats/AmbientStats.tsx
  src/components/Home/TopPools/TopPools.tsx
Labels: enhancement

#2660 Resizable trade table and chart
  package.json
  src/App/hooks/useTokenSearch.ts
  src/components/Global/TabComponent/TabComponent.tsx
  src/components/Global/TransactionDetails/TransactionDetailsGraph/TransactionDetailsGraph.tsx
  src/components/Trade/TradeTabs/Orders/Orders.tsx
  src/components/Trade/TradeTabs/PositionsOnlyToggle/PositionsOnlyToggle.tsx
  src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx
  src/components/Trade/TradeTabs/Ranges/Ranges.tsx
  src/components/Trade/TradeTabs/TradeTabs2.tsx
  src/components/Trade/TradeTabs/Transactions/Transactions.tsx
  src/contexts/ChartContext.tsx
  src/contexts/TradeTableContext.tsx
  src/pages/Chart/Chart.tsx
  src/pages/Trade/Trade.module.css
  src/pages/Trade/Trade.tsx
  src/pages/Trade/TradeCharts/TradeCharts.module.css
  src/pages/Trade/TradeCharts/TradeCharts.tsx
  src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.module.css
  src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.module.css
  src/pages/Trade/TradeCharts/TradeChartsHeader/TradeChartsHeader.tsx
  yarn.lock
Labels: needs-design-signoff

#2609 Create analytics page
  package.json
  src/App/App.css
  src/App/App.tsx
  src/App/components/PageHeader/PageHeader.tsx
  src/App/components/Sidebar/Sidebar.tsx
  src/App/components/Sidebar/SidebarAccordion/SidebarAccordion.tsx
  src/App/components/Sidebar/SidebarSearchResults/PoolsSearchResults/PoolsSearchResults.tsx
  src/App/functions/checkPoolForWETH.ts
  src/App/functions/getFormattedNumber.ts
  src/App/hooks/useFetchPoolStats.ts
  src/components/Global/Analytics/PoolRow.tsx
  src/components/Global/Analytics/TableHead.tsx
  src/components/Global/Analytics/TopPools.tsx
  src/components/Global/Analytics/useSortedPools.ts
  src/components/Global/PoolCard/PoolCard.tsx
  src/components/Global/SIdebarFooter/SidebarFooter.tsx
  src/components/Global/Sidebar/SidebarTable.module.css
  src/components/Global/Sidebar/TopPools/TopPools.tsx
  src/components/Global/TokensArrow/TokensArrow.module.css
  src/components/Home/Landing/Investors.module.css
  src/components/Home/Landing/Investors.tsx
  src/components/Home/Landing/TradeNowButton/TradeNowButton.tsx
  src/components/Home/Stats/AmbientStats.tsx
  src/components/Home/Stats/Stats.module.css
  src/components/Home/TopPools/TopPools.module.css
  src/components/Home/TopPools/TopPools.tsx
  src/contexts/ExploreContext.tsx
  src/contexts/GlobalContexts.tsx
  src/css/GlobalCssClassnames.css
  src/i18n/en/common.json
  src/i18n/kr/common.json
  src/i18n/zh/common.json
  src/index.css
  src/pages/Explore/Explore.tsx
  src/pages/TestPage/TestPage.module.css
  src/pages/TestPage/TestPage.tsx
  src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx
  src/utils/hooks/useLinkGen.ts
  src/utils/interfaces/PoolStatIF.ts
  src/utils/interfaces/exports.ts
  yarn.lock
Labels: needs-design-signoff

#2729 add spinner to `TopPools.tsx` in Explore module
  src/App/App.css
  src/components/Chat/ChatPanel.module.css
  src/components/Global/Analytics/Analytics.styles.ts
  src/components/Global/Analytics/PoolDisplay.module.css
  src/components/Global/Analytics/PoolDisplay.tsx
  src/components/Global/Analytics/PoolRow.tsx
  src/components/Global/Analytics/TableHead.tsx
  src/components/Global/Analytics/TokenDisplay.module.css
  src/components/Global/Analytics/TokenDisplay.tsx
  src/components/Global/Analytics/TopPools.tsx
  src/components/Global/Analytics/useSortedPools.ts
  src/contexts/ExploreContext.tsx
  src/contexts/SidebarContext.tsx
  src/pages/Explore/Explore.tsx
  src/pages/Explore/useTimeElapsed.ts
Labels: enhancement, needs-design-signoff
