Repository CrocSwap/ambient-ts-app, pull requests merged in 2023-11, with the labels that each got.

#3185 Fix clickable header logo
  src/App/components/PageHeader/NavbarDropdownMenu/NavbarDropdownItem.tsx
  src/App/components/PageHeader/NavbarDropdownMenu/NavbarDropdownMenu.tsx
  src/App/components/PageHeader/PageHeader.tsx
  src/constants/index.ts
  src/styled/Components/Header.ts
Labels: bug, look-and-feel

#3119 add gradient box shadow to containers with gradient borders
  src/components/Global/ContentContainer/ContentContainer.module.css
  src/components/Global/Modal/Modal.module.css
  src/components/Global/Modal/Modal.tsx
  src/components/Global/ModalHeader/ModalHeader.module.css
  src/components/Global/TokenSelectContainer/SoloTokenSelectModal.module.css
  src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx
  src/components/RangeActionModal/RangeActionModal.module.css
  src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
  src/index.css
  src/pages/InitPool/InitSkeleton.tsx
  src/styled/Common/Container.ts
  src/styled/Common/Types.ts
Labels: needs-design-signoff

#3195 Link canto
  src/App/components/PageHeader/NavbarDropdownMenu/NavbarDropdownMenu.tsx
  src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
  src/assets/images/networks/canto.png
  src/components/Footer/Footer.module.css
  src/components/Footer/Footer.tsx
  src/components/Footer/FooterCard.tsx
  src/styled/Components/Header.ts
Labels: enhancement, look-and-feel, needs-design-signoff, L2

#3188 add scroll token list to default lists in app
  public/ambient-token-list.json
  src/utils/data/defaultTokens.ts
  src/utils/data/stablePairs.ts
  src/utils/data/tokenListURIs.ts
  src/utils/networks/scrollMainnet.ts
Labels: L2, v1.6 - Oct. 20

#3201 Fix wallet dropdown balances
  src/App/components/PageHeader/Account/WalletDropdown/WalletDropdown.tsx
  src/utils/interfaces/NetworkIF.ts
Labels: bug, look-and-feel

#3207 Resequence networks in selector
  src/App/components/PageHeader/NetworkSelector/NetworkSelector.tsx
  src/constants/index.ts
  src/styled/Common/Text.ts
  src/utils/networks/scrollSepolia.ts
  src/utils/types/chainType.ts
  src/utils/types/index.ts
Labels: enhancement, look-and-feel, L2

#3151 Id fields for testing
  src/App/components/PageHeader/PageHeader.tsx
  src/App/components/Sidebar/Sidebar.tsx
  src/App/components/Sidebar/SidebarAccordion.tsx
  src/App/components/WalletModal/GateWallet.tsx
  src/App/components/WalletModal/WalletModalWagmi.tsx
  src/components/Form/Button.tsx
  src/components/Form/RangeWidth/RangeWidth.tsx
  src/components/Global/SlippageTolerance/SlippageTolerance.tsx
  src/components/Global/TabComponent/TabComponent.tsx
  src/components/Global/Tabs/TableMenu/TableMenuComponents/OrdersMenu.tsx
  src/components/Global/Tabs/TableMenu/TableMenuComponents/RangesMenu.tsx
  src/components/Global/TokenSelect/TokenSelect.tsx
  src/components/Global/TokenSelectContainer/SoloTokenImport.tsx
  src/components/Global/TransactionSettingsModal/TransactionSettingsModal.tsx
  src/components/Home/Landing/Hero.tsx
  src/components/Home/Landing/LandingSections.tsx
  src/components/Home/Landing/MobileLandingSections.tsx
  src/components/Home/Landing/TradeNowButton/TradeNowButton.tsx
  src/components/LimitActionModal/LimitActionModal.tsx
  src/components/LimitActionModal/LimitActionSettings/LimitActionSettings.tsx
  src/components/Portfolio/ExchangeBalance/Deposit/Deposit.tsx
  src/components/Portfolio/ExchangeBalance/ExchangeBalance.tsx
  src/components/Portfolio/ExchangeBalance/Transfer/Transfer.tsx
  src/components/Portfolio/ExchangeBalance/Transfer/TransferAddressInput.tsx
  src/components/Portfolio/ExchangeBalance/Withdraw/Withdraw.tsx
  src/components/RangeActionModal/RangeActionModal.tsx
  src/components/RangeActionModal/RangeActionSettings/RangeActionSettings.tsx
  src/components/RangeActionModal/RemoveRangeWidth/RemoveRangeWidth.tsx
  src/components/Trade/Limit/LimitRate/LimitRate.tsx
  src/components/Trade/Range/AdvancedModeComponents/PriceInput/PriceInput.tsx
  src/components/Trade/Range/AdvancedModeToggle/AdvancedModeToggle.tsx
  src/components/Trade/Range/RangePriceInfo/RangePriceInfo.tsx
  src/components/Trade/TradeModules/SubmitTransaction/TransactionFailed/TransactionFailed.tsx
  src/components/Trade/TradeModules/SubmitTransaction/TransactionSubmitted/TransactionSubmitted.tsx
  src/components/Trade/TradeModules/TradeConfirmationSkeleton.tsx
  src/components/Trade/TradeModules/TradeLinks.tsx
  src/components/Trade/TradeModules/TradeModuleHeader.tsx
  src/components/Trade/TradeModules/TradeModuleSkeleton.tsx
  src/components/Trade/TradeTabs/Transactions/Transactions.tsx
  src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
  src/pages/InitPool/FormExample.tsx
  src/pages/InitPool/InitButton.tsx
  src/pages/InitPool/InitConfirmation.tsx
  src/pages/InitPool/InitPool.tsx
  src/pages/InitPool/InitSettings.tsx
  src/pages/Portfolio/Portfolio.tsx
  src/pages/Trade/Limit/Limit.tsx
  src/pages/Trade/Range/Range.tsx
  src/pages/Trade/Reposition/Reposition.tsx
  src/pages/Trade/Swap/Swap.tsx
  src/pages/Trade/TradeCharts/TradeChartsComponents/TradeChartsTokenInfo.tsx
  src/styled/Components/TradeModules.ts
Labels: technical debt, med-prio, v1.7 - Nov. 2

#3216 Display transaction timestamp on laptop-sized screen
  src/components/Trade/TradeTabs/Transactions/Transactions.tsx
  src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
  src/styled/Components/TransactionTable.ts
Labels: enhancement

#3227 Refactor readme
  README.md
Labels: documentation

#3252 pass `urlParamMap.ts` to mobile version of trade route
  src/pages/Trade/Trade.tsx
Labels: bug, high-prio

#3244 Generic Analytics Batch Request Processor
  src/App/functions/fetchENSAddress.ts
  src/App/functions/fetchENSAddresses.ts
  src/App/functions/fetchTokenPrice.ts
  src/App/functions/getTransactionData.ts
  src/App/hooks/useFetchBatch.ts
  src/components/Trade/TradeTabs/Orders/OrderTable/OrderRow.tsx
  src/components/Trade/TradeTabs/Orders/Orders.tsx
  src/components/Trade/TradeTabs/Ranges/Leaderboard.tsx
  src/components/Trade/TradeTabs/Ranges/Ranges.tsx
  src/components/Trade/TradeTabs/Ranges/RangesTable/RangesRow.tsx
  src/components/Trade/TradeTabs/Transactions/Transactions.tsx
  src/components/Trade/TradeTabs/Transactions/TransactionsTable/TransactionRow.tsx
  src/constants/index.ts
  src/contexts/ENSAddressContext.tsx
  src/contexts/GlobalContexts.tsx
  src/styled/Components/TransactionTable.ts
  src/utils/functions/fetchBatch.ts
  src/utils/functions/fetchTimeout.ts
  src/utils/hooks/useProcessOrder.ts
  src/utils/hooks/useProcessRange.ts
  src/utils/hooks/useProcessTransaction.ts
  src/utils/types/fetchBatch.ts
  src/utils/types/index.ts
Labels: enhancement
