Repository CrocSwap/ambient-ts-app, pull requests merged in 2024-02, with the labels that each got.

#3368 fix position hash mismatch in reposition header
  src/components/Trade/Reposition/RepositionHeader/RepositionHeader.tsx
  src/pages/Trade/Reposition/Reposition.tsx
Labels: bug

#3417 Collapse sidebar by default
  src/App/hooks/useSidebar.ts
  src/contexts/SidebarContext.tsx
Labels: enhancement, low-prio

#3461 Update l2 slippage
  src/App/hooks/useSlippage.ts
  src/ambient-utils/constants/slippage.ts
  src/contexts/ChainDataContext.tsx
  src/contexts/UserPreferenceContext.tsx
Labels: high-prio, L2
